name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: betaserver

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install via npm
      run: npm i
    
    - name: Run the process
      run: bash startMe.sh # see the script

    - name: send webhook
      run: node .github/sendwebhook.js ${{secrets.DISCORD_URL}} ${{secrets.AMELIAENDPOINT}} ${{secrets.TEL}} ${{secrets.KEY}}